libs/yumeblog/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from yumeblog.feeds import LatestPosts

from django.contrib import admin
admin.autodiscover()
import os

feeds = { 'latest': LatestPosts, }

urlpatterns = patterns('',   
   (r'^fckeditor/',include('fckeditor.urls')),
   
   #index
   url(r'^index$','yumeblog.views.list_post',{'template_name':'list.htm'},name='blog_index'),
   
   #static files
   (r'^admin/(.*)', admin.site.root),
   (r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
   (r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
   url(r'^style/(?P<path>.*)$','django.views.static.serve',{'document_root':os.path.join(settings.TEMPLATE_BLOG_ROOT,'style')},name='get_blog_media_file'),

   #post list
   url(r'^tag/(?P<tag>[^/]+)/$','yumeblog.views.list_post',{'template_name':'list.htm'},name='list_post_by_tag'),
   url(r'^search/(?P<keyword>[^/]+)/$','yumeblog.views.list_post',{'template_name':'list.htm'},name='list_post_by_keyword'),
   url(r'^$','yumeblog.views.list_post',{'template_name':'list.htm'},name="list_post"),
   
   #comments
   
   #feeds
   url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',{'feed_dict': feeds},name="get_feed"),
   
   #page
   url(r'^page/(?P<slug>\S+)/$', 'yumeblog.views.show_page',{'template_name':'page.htm'},name="get_page_by_slug"),
   
   #single post
   url(r'^(?P<pk>\d+)/$', 'yumeblog.views.show_post',{'template_name':'post.htm'},name="get_post_by_id"),
   url(r'^(?P<slug>\S+)/$', 'yumeblog.views.show_post',{'template_name':'post.htm'},name="get_post_by_slug"),
   
)

handler404 = 'yumeblog.views.handler404'
handler500 = 'yumeblog.views.handler500'

myblog/urls.py
from django.conf.urls.defaults import *

from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    #blog urls
    #(r'^YOUR_INSTANCE_NAME/',include('yumeblog.urls')),
    (r'^myblog/',include('yumeblog.urls')),
)

handler404 = 'yumeblog.views.handler404'
handler500 = 'yumeblog.views.handler500'

libs/yumeblog/models.py
from django.db import models

from fckeditor.fields import RichTextField
from tagging.fields import TagField
from django.contrib.sites.models import Site

from datetime import datetime

from django.utils.translation import ugettext as _
from django.contrib.sites.managers import CurrentSiteManager
from django.conf import settings

COMMENT_MAX_LENGTH = getattr(settings,'COMMENT_MAX_LENGTH',3000)

class SiteInfoManager(models.Manager):
    def get_current(self):
        return SiteInfo.objects.filter(site = Site.objects.get_current())[0]

class SiteInfo(models.Model):
    title = models.CharField(_('Title'),max_length=100)
    subtitle = models.CharField(_('Subtitle'),max_length=255)
    description = models.TextField(_('description'))
    copyright = models.TextField(_('Copyright in HTML'))
    copyright_plain_text = models.CharField(_('Copyright in Plain Text'),max_length=250,null=True,blank=True)
    keywords = models.CharField(_('Keyword'),max_length=100)
    site = models.OneToOneField(Site,default=settings.SITE_ID)
    feed = models.URLField(_('Custom Feed URL'), blank=True)
    
    objects = SiteInfoManager()
    
    def __unicode__(self):
        return self.title

class Menu(models.Model):
    "Navi-bar"
    title = models.CharField(_("Title"),max_length=255)
    url = models.CharField(_('URL'),max_length=255)
    site = models.ForeignKey(Site,default=settings.SITE_ID)
    objects = CurrentSiteManager()
    
    def __unicode__(self):
        return self.title

class Link(models.Model):
    "Links"
    title = models.CharField(_("Title"),max_length=255)
    url = models.URLField(_("URL"),max_length=255)
    relation = models.CharField(_("Type"),default='friend',max_length=20)
    site = models.ForeignKey(Site,default=settings.SITE_ID)
    description = models.TextField(_('description'))
    objects = CurrentSiteManager()
    
    def __unicode__(self):
        return self.title

class Page(models.Model):
    "Blog's page"
    title = models.CharField(_("Title"),max_length=255)
    slug = models.SlugField(_("Slug"),max_length=255)
    content = RichTextField(_("Content"))
    site = models.ManyToManyField(Site,default=[settings.SITE_ID,])
    objects = CurrentSiteManager()
    updated = models.DateTimeField(_("Modified"),auto_now=True)
    created = models.DateTimeField(_("Created"),default=datetime.now)

    class Meta:
        ordering = ['-created']
        
    def __unicode__(self):
        return self.title

class PublicPostManager(CurrentSiteManager):
    def get_query_set(self):
        return super(PublicPostManager,self).get_query_set().filter(is_public=True)

class Post(models.Model):
    "Blog's posts"
    title = models.CharField(_("Title"),max_length=255)
    slug = models.SlugField(_("Slug"),max_length=255)
    content = RichTextField(_("Content"))
    intro = RichTextField(_("Brief introduction"),null=True,blank=True)
    tags = TagField(_("Tags"))
    
    site = models.ForeignKey(Site,default=settings.SITE_ID)
    objects = CurrentSiteManager()
    public_objects = PublicPostManager()

    is_public = models.BooleanField(_('is public'), default = True)
    
    updated = models.DateTimeField(_("Modified"),auto_now=True)
    created = models.DateTimeField(_("Created"),default=datetime.now)

    class Meta:
        ordering = ['-created','-id',]
        
    def __unicode__(self):
        return self.title

#TODO
#class CommentManager(CurrentSiteManager):
#    pass

class Comment(models.Model):
    "Post's Comment"
    user_name   = models.CharField(_("name"), max_length=50)
    user_email  = models.EmailField(_("email address"))
    user_url    = models.URLField(_("homepage"), blank=True)
    
    comment = models.TextField(_('comment'), max_length=COMMENT_MAX_LENGTH)
    
    ip_address  = models.IPAddressField(_('ip address'), blank=True, null=True)
    useragent  = models.CharField(_("user agent string"), max_length=100, blank=True, null=True)
    
    post = models.ForeignKey(_('post'))
    parent = models.ForeignKey('self',related_name='children',default=None,null=True,blank=True)
    
    site = models.ForeignKey(Site,default=settings.SITE_ID)
    objects = CurrentSiteManager()
    
    is_public = models.BooleanField(_('is public'), default = True)
    is_notice = models.BooleanField(_('receive email notify'), default = True)
    
    updated = models.DateTimeField(_("Modified"),auto_now=True)
    created = models.DateTimeField(_("Created"),default=datetime.now())
    
    #Inspired by http://www.djangosnippets.org/snippets/112/
    # &http://www.voidspace.org.uk/python/modules.shtml#akismet
    def comment_check(self):
        '''
        Check a comment.
        Return True for ham, False for spam.
        Use this function before save a comment.
        '''
        try:
            if hasattr(settings, 'BAN_NON_CJK') and settings.BAN_NON_CJK:
                import re
                if not re.search(ur"[\u4E00-\u9FC3\u3041-\u30FF]",self.comment):
                    raise Exception()
                
            if hasattr(settings, 'AKISMET_API_KEY') and settings.AKISMET_API_KEY:
                from akismet import Akismet
                akismet_api = Akismet(key=settings.AKISMET_API_KEY, blog_url='http://%s/' % Site.objects.get_current().domain)
                if akismet_api.verify_key():
                    akismet_data = { 'comment_type': 'comment',
                                    'user_ip':self.ip_address,
                                    'user_agent':self.user_agent,
                                    'referrer':'',
                                    }
                    return not akismet_api.comment_check(self.comment.encode("utf8"), data=akismet_data, build_data=True)
            else:
                return True
        except:
            return False

    class Meta:
        ordering = ['-updated']
        
    def __unicode__(self):
        return self.comment
    
from django.db.models import signals
from django.dispatch import dispatcher

from models import Comment

libs/yumeblog/forms.py
from django import forms
from django.forms.models import modelformset_factory
from django.db import models
from django.utils.translation import ugettext as _

from models import Comment,COMMENT_MAX_LENGTH

class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label = _('Leave a comment'),
        max_length = COMMENT_MAX_LENGTH,
        widget = forms.Textarea
    )
    class Meta:
        model = Comment
        fields = ('user_name', 'user_email', 'user_url', 'comment', 'parent', 'is_notice')

libs/yumeblog/views.py
from models import Post,Page,Comment,SiteInfo
from forms import CommentForm
from tagging.models import Tag,TaggedItem

from django.conf import settings

from django.utils.translation import ugettext as _

from django.template import RequestContext, loader
from django.shortcuts import render_to_response
from django.http import Http404,HttpResponse,HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, InvalidPage, EmptyPage

from django.core.mail import EmailMessage

from django.db.models import Q
from hashlib import md5

from useragent.uasparser import UASparser

def show_post(request,template_name='post.htm',pk=None,slug=None):
    '''
    Show a single post by post's slug or primarykey
    '''
    msg = {'message':'',
           'type_str':'',
           'type_code':'',
           }

    try:
        if slug is not None:
            post = Post.public_objects.get(slug=slug)
        else:
            post = Post.public_objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        lastest_comment = md5(request.POST['comment'].encode('utf-8')).hexdigest()

        if request.session.get('LASTEST_COMMENT','') == lastest_comment :
            msg['message'] = _('You\'ve already commented.')
            msg['type_str'] = _('Alert')
            msg['type_code'] = 'ALERT'
        elif form.is_valid():
            #before save
            comment = form.save(commit=False)
            comment.post = post
            comment.ip_address = request.META['REMOTE_ADDR']
            
            if comment.comment_check(): #Start Moderation
                #fetch user agent string
                #uas_parser = UASparser()
                #uas_data = uas_parser.parse(request.META['HTTP_USER_AGENT'])
                #comment.useragent = "%s||%s" % ( uas_data['ua_name'], uas_data['os_name'] )
                comment.useragent = request.META['HTTP_USER_AGENT']
                
                #save
                comment.save()

                #send notify
                msg['message'] = _('Your comment has submited successfully.')
                msg['type_code'] = 'SUCCESS'
                request.session['LASTEST_COMMENT'] = md5(comment.comment.encode('utf8')).hexdigest()
                if comment.parent and comment.parent.is_notice and hasattr(settings,'EMAIL_HOST_USER'): #Send mail
                    site = SiteInfo.objects.get_current()
                    subject = _("Your comment over at %s now have new reply" % site.title)
                    html_content = loader.render_to_string("email-notify.htm",{
                                                                'site':site,
                                                                'post':post,
                                                                'original':comment.parent,
                                                                'reply':comment,
                                                                               })
                    recipient_list = [comment.parent.user_email,]
                    mail = EmailMessage(subject, html_content, settings.EMAIL_HOST_USER, recipient_list)
                    mail.content_subtype = "html"
                    mail.send()
            else:
                comment.is_public = False
                if hasattr(settings, 'DELETE_SPAM_COMMENT') and not settings.DELETE_SPAM_COMMENT:
                    comment.save()
                msg['message'] = _('Your comment is under medoration.')
                msg['type_str'] = _('Submitd')
                msg['type_code'] = 'ALERT'
            
            form = CommentForm()
                
        else:
            msg['message'] = _('Please check the form and try again.')
            msg['type_str'] = _('Submit failed')
            msg['type_code'] = 'ERROR'
        
    else:
        form = CommentForm()
        
    try:    #Try to initial user info to form
        if ( request.COOKIES.has_key('BLOG_USERNAME') and 
             request.COOKIES.has_key('BLOG_USEREMAIL') and 
             request.COOKIES.has_key('BLOG_USERURL') and
            request.COOKIES.has_key('IS_NOTICE') and
            not form.errors ):
            form = CommentForm(initial={
                            'user_name':request.COOKIES['BLOG_USERNAME'],
                            'user_email':request.COOKIES['BLOG_USEREMAIL'],
                            'user_url':request.COOKIES['BLOG_USERURL'],
                            'is_notice':request.COOKIES['IS_NOTICE'],
                            })
    except:
        pass
    
    response = render_to_response(template_name,
                              {'post':post,
                               'form':form,
                               'msg':msg,
                               },
                              context_instance=RequestContext(request))
    try:
        max_age = 3600*24*365
        response.set_cookie('BLOG_USERNAME', comment.user_name, max_age)
        response.set_cookie('BLOG_USEREMAIL', comment.user_email, max_age)
        response.set_cookie('BLOG_USERURL', comment.user_url, max_age)
        response.set_cookie('IS_NOTICE', comment.is_notice, max_age)
    except:
        pass
        
    return response
        

def show_page(request,template_name='page.htm',slug=None):
    '''
    Show a single page by post's slug or primarykey
    '''
    try:
        if slug is not None:
            page = Page.objects.get(slug=slug)
    except Page.DoesNotExist:
        raise Http404
    return render_to_response(template_name,
                              {'page':page},
                              context_instance=RequestContext(request))

def list_post(request,template_name='list.htm',tag=None,keyword=None):
    '''
    List post by tag or keyword
    '''

    # check if tag available
    if tag is None:
        post_list = Post.public_objects.all()
        if keyword is not None:
            post_list = post_list.filter(
                            Q(title__contains=keyword)|
                            Q(content__contains=keyword)
                        )
    else:
        tag = Tag.objects.get(name=tag)
        post_list = TaggedItem.objects.get_by_model(Post,tag).filter(is_public=True)
    paginator = Paginator( post_list, getattr(settings, 'ITEM_COUNT_PER_PAGE', 8))
    
    # setup the pagination
    try:
        page = int(request.GET.get('page',1))
    except ValueError:
        page = 1
    
    try:
        posts = paginator.page(page)
    except ( EmptyPage, InvalidPage ):
        posts = paginator.page(paginator._num_pages)
      
    if tag is not None:
        posts.list_by = tag
        posts.list_type = 'TAG'
    elif keyword is not None:
        posts.list_by = keyword
        posts.list_type = 'SEARCH'
    # render the template
    return render_to_response(template_name,
                              {'posts':posts},
                              context_instance=RequestContext(request))
                              
def handler404(request):
    return show_page(request,slug='404')
    
def handler500(request):
    return show_page(request,slug='500')

libs/yumeblog/templates/default/base.htm
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
{% load i18n %}{% load tagging_tags %}{% load blog_tags %}
{% get_siteinfo as site %}
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="ROBOTS" content="ALL" />
<meta name="copyright" content="{{ site.copyright_plain_text|default:site.copyright }}" />
<meta name="keywords" content="{{ site.keywords }}{% block keywords %}{{ site.title }}{% endblock %}" />
<meta name="description" content="{{ site.description }}" />
<link rel="stylesheet" type="text/css" charset="utf-8" media="all" href="{% url get_blog_media_file "common.css" %}">
<link rel="alternate" type="application/rss+xml" title="{% blocktrans with site|title as site_title %}{{ site_title }}'s RSS Feed{% endblocktrans %}" href="{% if site.feed %}{{ site.feed }}{% else %}{% url get_feed "latest" %}{% endif %}" />
<link rel="SHORTCUT ICON" href="{% url get_blog_media_file "favicon.ico" %}"/>
<script language="JavaScript" src="{% url get_blog_media_file "js/mootools-1.2.1-core.js" %}"></script>
<script language="JavaScript" src="{% url get_blog_media_file "js/core.js" %}"></script>
<title>{% block title %}FrontPage{% endblock %} || {{ site.title }} </title>
</head>
<body>
<div id="wrapper">
<div id="header">
<div id="logo">
	<h1><a href="{% url blog_index %}">{{ site.title }}</a></h1>
<p id="description">{{ site.subtitle }}<a type="application/rss+xml" href="{% if site.feed %}{{ site.feed }}{% else %}{% url get_feed "latest" %}{% endif %}" title="Entries RSS">(#)</a></p>
</div>
<ul id="navibar">
{% get_menuitems as menuitems %}
{% for menuitem in menuitems  %}
<li><a href="{{ menuitem.url }}">{{ menuitem.title}}</a></li>
{% endfor %}
</ul>
</div>
<div id="posts">
<span class="hidden">{% trans "Latest Comments:"%}</span>
<ul class="latest-comments">
	{% get_latest_comments 15 as comments_list%}
{% for comment in comments_list %}<li><a href="{% url get_post_by_id comment.post.pk %}#COMMENT-{{ comment.pk }}" title="{{ comment.comment }}"><img src="{% gravatar_url comment.user_email 24 'g' identicon%}" alt="{{ comment.user_name}}"/></a><p class="hidden">{{ comment.comment }}</p></li>{% endfor %}
</ul>
{# ----------MESSAGE----------- #}
{% block message %}
{% if msg.type_code %}
<div class="message">
<span>{% if msg.type_str %}<em>{{ msg.type_str }}:</em>{% endif %}{{ msg.message }}</span>
</div>
{% endif %}
{% endblock %}
{# ----------CONTENT----------- #}
{% block content %}{% endblock %}
<div id="info">
{# ----------INFO----------- #}
{% block info %}
{% if site.description %}
<h3>{% trans "Description::" %}</h3>
<p class="description">{{ site.description|safe }}</p>
{% endif %}
{# -->TAG #}
{% tag_cloud_for_model yumeblog.Post as post_tags with steps=5 min_count=2 distribution=linear %}
{% if post_tags %}
<h3>{% trans "Tags::" %}</h3>
<ul>
{% for tag in post_tags %}
<li><a href="{% url list_post_by_tag tag%}" style="font-size:1.{{ tag.font_size }}em;">{{ tag }}({{ tag.count }})</a></li>
{% endfor %}
</ul>
{% else %}
<h3>{% trans "No Tag" %}</h3>
{% endif %}
{% get_latest yumeblog.Link 20 as latest_link_list %}
{% if latest_link_list %}
<h3>{% trans "Links::" %}</h3>
<ul>
{% for link in latest_link_list %}
<li><a href="{{ link.url }}" title="{{ link.title }}" rel="{{ link.relation }}" target="_blank">{{ link.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<h3>{% trans "No Link" %}</h3>
{% endif %}
{% endblock %}
</div>
</div>
<div id="footer">
{{ site.copyright|safe }}
</div>
</div>
</body>
</html>

libs/yumeblog/templates/default/email-notify.htm
{% load i18n %}{% load blog_tags %}
{% blocktrans with site|title as site_title and post|title as post_title %}
<p></p><b>{{ site_title }}</b> inform respectfully: your comment on post <b>{{ post_title }}</b> now have new reply.</p>
{% endblocktrans %}
<hr/>
<p>{% trans "here is your comment:" %}</p>
<p>{{ original.comment|linebreaksbr|escape }}</p>
<br/>
<p>{% trans "here is new reply comment:" %}</p>
<p>{{ reply.comment|linebreaksbr|escape }}</p>
<hr/>
<p>{% trans "You can see detail for the comment on this post here:" %}</p>
<p><a href="http://{{ site.site.domain}}{% url get_post_by_slug post.slug %}#COMMENT-{{ reply.pk }}">http://{{ site.site.domain}}{% url get_post_by_slug post.slug %}#COMMENT-{{ reply.pk }}</a></p>
<p>{% trans "Or check the latest posts"%}</p>
<p><b><a href="http://{{ site.site.domain }}{% url blog_index %}">{{ site.title }}</a></b></p>
<p>{% trans "Or subscribe the RSS here:" %}</p>
<p><b><a href="{% if site.feed %}{{ site.feed }}{% else %}http://{{ site.site.domain }}{% url get_feed "latest" %}{% endif %}">{% if site.feed %}{{ site.feed }}{% else %}http://{{ site.site.domain }}{% url get_feed "latest" %}{% endif %}</a></b></p>

libs/yumeblog/templates/default/list.htm
{% extends 'base.htm' %}
{% load blog_tags %}{% load tagging_tags %}{% load i18n %}
{% if posts.list_by %}
{% block keywords %}{{ posts.list_by }}{% endblock %}
{% endif %}
{# ----------Title----------- #}
{% block title %}
{% trans "Entries" %}{% if posts.list_by %}::{{ posts.list_by }}{% endif %}
{% endblock%}
{# ----------MESSAGE----------- #}
{% block message %}
{% if posts.list_by %}
<div class="message">
<span>
{% ifequal posts.list_type 'TAG' %}<em>{% trans "Tags:"%}</em>{{ posts.list_by }}{% endifequal %}
{% ifequal posts.list_type 'SEARCH' %}<em>{% trans "Keyword:"%}</em>{{ posts.list_by }}{% endifequal %}
</span>
</div>
{% endif %}
{% endblock %}
{# ----------Content----------- #}
{% block content %}
{% if posts.object_list %}
{% for post in posts.object_list %}
	{% tags_for_object post as tag_list %}
<div class="post">
<h1><a href="{% url get_post_by_slug post.slug %}">{{ post.title|escape }}</a></h1>
<p class="date">{{ post.created|date:"j N Y" }}</p>
<div class="entry">{{ post.intro|default:post.content|safe }}</div>
<div class="clearfix"></div>
{% if post.intro %}
<div class="rest-of-entry"><a href="{% url get_post_by_slug post.slug %}">{% trans "Read the rest of the entry" %}</a></div>
{% endif %}
<p class="tags">
{% if tag_list %}
{% trans "Tags::" %}{% for tag in tag_list %}<a href="{% url list_post_by_tag tag%}">{{ tag }}</a>{% endfor %}
{% else %}
{% trans "No Tag"%}
{% endif %}
</p>
{% get_comments_count for post as comments_count %}
<p class="num-of-comments"><a title="post's comments" href="{% url get_post_by_slug post.slug %}#COMMENT">{% if comments_count %}{% blocktrans count comments_count as count %}{{ count }} comment{% plural %}{{ count }} comments{% endblocktrans %}{% else %}{% trans 'no comment is a comment'%}{% endif%}</a></p>
</div>
{% endfor %}
{% else %}
<div class="message">
<span>{% trans 'No matched entry.' %}</span>
</div>
{% endif %}
<div class="page-nav">
{% if posts.has_next %}
<a class="page-prev" href="?page={{ posts.next_page_number }}">{% trans "<< Older Entries" %}</a>
{% endif %}

{% if posts.has_previous %}
<a class="page-next" href="?page={{ posts.previous_page_number }}">{% trans "Newer Entries >>" %}</a>
{% endif %}

{% if posts.has_previous or posts.has_next %}<div class="clearfix"></div>{% endif %}
</div>

{% endblock %}

libs/yumeblog/templates/default/page.htm
{% extends 'base.htm' %}
{% load blog_tags %}{% load tagging_tags %}{% load i18n %}
{# ----------Title----------- #}
{% block title %}{{ page.title }}{% endblock%}
{# ----------Content----------- #}
{% block content %}
<div class="post">
<h1><a href="{% url get_page_by_slug page.slug %}">{{ page.title|escape }}</a></h1>
<p class="date">{{ page.created|date:"j N Y" }}</p>
<div class="entry">{{ page.content|safe }}</div>
<div class="clearfix"></div>
</div>
{% endblock %}

libs/yumeblog/templates/default/post.htm
{% extends 'base.htm' %}
{% load blog_tags %}{% load tagging_tags %}{% load i18n %}
{# ----------Keyword----------- #}
{% block keywords %}{% for tag in tag_list %}{{ tag }},{% endfor %}{% endblock %}
{# ----------Title----------- #}
{% block title %}{{ post.title }}{% endblock%}
{# ----------Content----------- #}
{% block content %}
{% tags_for_object post as tag_list %}
{% get_comments for post as comments_list %}
{% get_related_posts post 5 as related_posts %}
<div class="post">
<h1><a href="{% url get_post_by_slug post.slug %}">{{ post.title|escape }}</a></h1>
<p class="date">{{ post.created|date:"j N Y" }}</p>
<div class="entry">{{ post.content|safe }}</div>
<div class="clearfix"></div>
{% if related_posts %}
<h3 class="related-label">{% trans 'Related entries'%}</h3>
<ul class="related">
	{% for rel_post in related_posts %}
	<li><a href="{% url get_post_by_slug rel_post.slug %}">{{ rel_post.title|escape }}</a></li>
	{% endfor %}
</ul>
<h3 class="related-label">{% trans 'Latest entries'%}</h3>
<ul class="related">
    {% get_latest yumeblog.Post 5 as latest_posts %}
	{% for new_post in latest_posts %}
	<li><a href="{% url get_post_by_slug new_post.slug %}">{{ new_post.title|escape }}</a></li>
	{% endfor %}
</ul>
{% endif %}
<p class="tags">
{% if tag_list %}
{% trans "Tags::" %}{% for tag in tag_list %}<a href="{% url list_post_by_tag tag%}">{{ tag }}</a>{% endfor %}
{% else %}
{% trans "No Tag"%}
{% endif %}
</p>
{% get_comments_count for post as comments_count %}
<p class="num-of-comments"><a title="post's comments" href="{% url get_post_by_slug post.slug %}#COMMENT">{% if comments_count %}{% blocktrans count comments_count as count %}{{ count }} comment{% plural %}{{ count }} comments{% endblocktrans %}{% else %}{% trans 'no comment is a comment'%}{% endif%}</a></p>
</div>
<a name="COMMENT">
<div id="comment-box">
{% nested_comment comments_list as comment %}
<ul>
{% loop %}
<li id="comment-{{ comment.pk }}">
	<h4><a href="{{ comment.user_url }}" name="COMMENT-{{ comment.pk }}">{{ comment.user_name }}</a>@<sup>{{ comment.created|date:"j N Y" }}</sup></h4>
	<img src="{% gravatar_url comment.user_email 48 'g' identicon%}" alt="{{ comment.user_name }}"/>
	<a class="reply" onclick="show_reply({{ comment.pk }});">{% trans "Reply" %}</a>
	<p>{{ comment.comment|linebreaksbr|escape }}</p>
{% children %}
</li>
{% endloop %}
</ul>
{% end_nested_comment%}
</div>
</a>
<form id="comment-form" action="." method="post" onsubmit="$('submit-comment').set('disabled','true').setStyle('color','#555');">
<ul>
<li><label for="id_user_name">{{ form.user_name.label }}</label>{{ form.user_name }}<em>{{ form.user_name.errors }}</em></li>
<li><label for="id_user_email">{{ form.user_email.label }}</label>{{ form.user_email }}<em>{{ form.user_email.errors }}</em></li>
<li><label for="id_user_url">{{ form.user_url.label }}</label>{{ form.user_url }}<em>{{ form.user_url.errors }}</em></li>
<li><label for="id_comment">{{ form.comment.label }}</label>{{ form.comment }}<em>{{ form.comment.errors }}</em></li>
<li><label for="id_notice" class="checkbox-label">{{ form.is_notice.label }}</label>{{ form.is_notice }}<em>{{ form.is_notice.errors }}</em></li>
<li><input type="submit" value="{% trans "Submit your comment."%}" id="submit-comment"/></li>
<li><input type="hidden" value="" name="parent" id="id_parent"/></li>
</ul>
</form>
{% endblock %}